

export const metadata = {
  title: 'Qatar Living',
  description: 'Generated by Ameer',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          {children}
      </body>
    </html>
  )
}