import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-bodyFont bg-qatar_body">
        <main className='max-w-screen-maxW m-auto lg:pl-[15px] lg:pr-[15px]'>
          {children}
        </main>
      </body>
    </html>
  )
}
