import './globals.css'


export const metadata = {
  title: 'Qatar Living',
  description: 'Generated by Ameer',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-bodyFont bg-qatar_body">
          {children}
      </body>
    </html>
  )
}
